name: publish

on:
  push:
    branches: [ main ]
    
env:
  DOTNET_VERSION: 6.x # The .NET SDK version to use
 
jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore src/PaymentProto
    - name: Build
      run: dotnet build src/PaymentProto --configuration Release --no-restore
    - name: Pack the project
      run: dotnet pack src/PaymentProto --configuration Release --output .
    - name: Publish the package to GitHub Packages
      run: dotnet nuget push PaymentProto.*.nupkg -s https://nuget.pkg.github.com/taboo09/index.json -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate