name: publish

on:
  push:
    branches: [ main ]
    
env:
  DOTNET_VERSION: 6.x # The .NET SDK version to use
 
jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies Server package
      run: dotnet restore src/PaymentProto
    - name: Install dependencies Client package
      run: dotnet restore src/PaymentProtoClient

    - name: Build Server package
      run: dotnet build src/PaymentProto --configuration Release --no-restore
    - name: Build Client package
      run: dotnet build src/PaymentProtoClient --configuration Release --no-restore
      
    - name: Pack the Server project
      run: dotnet pack src/PaymentProto --configuration Release --output .
    - name: Pack the Client project
      run: dotnet pack src/PaymentProtoCLient --configuration Release --output .
    - name: Publish the package to GitHub Packages
      run: dotnet nuget push PaymentProto.*.nupkg -s https://nuget.pkg.github.com/taboo09/index.json -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate